//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFeRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class PapierosyEntity
    {
        public PapierosyEntity()
        {
            this.papierosy_ceny = new HashSet<Papierosy_cenyEntity>();
            this.wyjazdy = new HashSet<WyjazdyEntity>();
        }
    
        public int id_papierosy { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<Papierosy_cenyEntity> papierosy_ceny { get; set; }
        public virtual ICollection<WyjazdyEntity> wyjazdy { get; set; }
    }
}
