//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFeRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Papierosy_cenyEntity
    {
        public int id_papierosy_ceny { get; set; }
        public int id_papierosy { get; set; }
        public int id_przejscia { get; set; }
        public int id_sklepy { get; set; }
        public Nullable<decimal> cena_paczka { get; set; }
        public Nullable<decimal> cena_pakiet { get; set; }
    
        public virtual PapierosyEntity papierosy { get; set; }
        public virtual PrzejsciaEntity przejscia { get; set; }
        public virtual SklepyEntity sklepy { get; set; }
    }
}
