//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFeRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class UzytkownicyEntity
    {
        public UzytkownicyEntity()
        {
            this.wyjazdy = new HashSet<WyjazdyEntity>();
        }
    
        public int id_uzytkownicy { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public string email { get; set; }
        public System.DateTime zarejestrowano { get; set; }
        public Nullable<System.DateTime> ostatnie_logowanie { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<WyjazdyEntity> wyjazdy { get; set; }
    }
}
