//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFeRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class WyjazdyEntity
    {
        public int id_wyjazdy { get; set; }
        public int id_uzytkownicy { get; set; }
        public int id_przejscia { get; set; }
        public int id_stacje_benzynowe { get; set; }
        public int id_paliwa { get; set; }
        public decimal ilosc_paliwa { get; set; }
        public Nullable<int> id_alkohole { get; set; }
        public Nullable<int> id_sklepy_alkohole { get; set; }
        public Nullable<decimal> ilosc_alkoholu { get; set; }
        public Nullable<int> id_papierosy { get; set; }
        public Nullable<int> id_sklepy_papierosy { get; set; }
        public Nullable<int> ilosc_papierosow { get; set; }
        public System.DateTime data { get; set; }
        public int kanal { get; set; }
        public int mandat { get; set; }
    
        public virtual AlkoholeEntity alkohole { get; set; }
        public virtual PaliwaEntity paliwa { get; set; }
        public virtual PapierosyEntity papierosy { get; set; }
        public virtual PrzejsciaEntity przejscia { get; set; }
        public virtual SklepyEntity sklepy { get; set; }
        public virtual SklepyEntity sklepy1 { get; set; }
        public virtual Stacje_benzynoweEntity stacje_benzynowe { get; set; }
        public virtual UzytkownicyEntity uzytkownicy { get; set; }
    }
}
