#pragma checksum "C:\Users\Paweł\documents\visual studio 2013\Projects\WCFeRosja\eRosja\Strony\Ceny.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "6C832A88FE2A4CC8CE9C75CBBE508FE0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Phone.Controls;
using System;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Automation.Peers;
using System.Windows.Automation.Provider;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Resources;
using System.Windows.Shapes;
using System.Windows.Threading;


namespace eRosja {
    
    
    public partial class Ceny : Microsoft.Phone.Controls.PhoneApplicationPage {
        
        internal System.Windows.Controls.Grid LayoutRoot;
        
        internal Microsoft.Phone.Controls.PivotItem pivotPaliwo;
        
        internal Microsoft.Phone.Controls.ListPicker lpPrzejscia;
        
        internal Microsoft.Phone.Controls.ListPicker lpStacje;
        
        internal System.Windows.Controls.Grid gridCenyPaliw;
        
        internal System.Windows.Controls.Grid gridNazwyPaliw;
        
        internal System.Windows.Controls.TextBlock tbNazwaStacji;
        
        internal System.Windows.Controls.TextBlock tbPaliwo1;
        
        internal System.Windows.Controls.TextBlock tbPaliwo2;
        
        internal System.Windows.Controls.TextBlock tbPaliwo3;
        
        internal System.Windows.Controls.TextBlock tbPaliwo4;
        
        internal System.Windows.Controls.TextBlock tbPaliwo5;
        
        internal System.Windows.Controls.TextBlock tbPaliwo6;
        
        internal System.Windows.Controls.TextBlock tbCena1;
        
        internal System.Windows.Controls.TextBlock tbCena2;
        
        internal System.Windows.Controls.TextBlock tbCena3;
        
        internal System.Windows.Controls.TextBlock tbCena4;
        
        internal System.Windows.Controls.TextBlock tbCena5;
        
        internal System.Windows.Controls.TextBlock tbCena6;
        
        internal Microsoft.Phone.Controls.ListPicker lpSklepy;
        
        internal Microsoft.Phone.Controls.ListPicker lpPrzejsciaPapierosy;
        
        internal Microsoft.Phone.Controls.ListPicker lpPapierosy;
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Windows.Application.LoadComponent(this, new System.Uri("/eRosja;component/Strony/Ceny.xaml", System.UriKind.Relative));
            this.LayoutRoot = ((System.Windows.Controls.Grid)(this.FindName("LayoutRoot")));
            this.pivotPaliwo = ((Microsoft.Phone.Controls.PivotItem)(this.FindName("pivotPaliwo")));
            this.lpPrzejscia = ((Microsoft.Phone.Controls.ListPicker)(this.FindName("lpPrzejscia")));
            this.lpStacje = ((Microsoft.Phone.Controls.ListPicker)(this.FindName("lpStacje")));
            this.gridCenyPaliw = ((System.Windows.Controls.Grid)(this.FindName("gridCenyPaliw")));
            this.gridNazwyPaliw = ((System.Windows.Controls.Grid)(this.FindName("gridNazwyPaliw")));
            this.tbNazwaStacji = ((System.Windows.Controls.TextBlock)(this.FindName("tbNazwaStacji")));
            this.tbPaliwo1 = ((System.Windows.Controls.TextBlock)(this.FindName("tbPaliwo1")));
            this.tbPaliwo2 = ((System.Windows.Controls.TextBlock)(this.FindName("tbPaliwo2")));
            this.tbPaliwo3 = ((System.Windows.Controls.TextBlock)(this.FindName("tbPaliwo3")));
            this.tbPaliwo4 = ((System.Windows.Controls.TextBlock)(this.FindName("tbPaliwo4")));
            this.tbPaliwo5 = ((System.Windows.Controls.TextBlock)(this.FindName("tbPaliwo5")));
            this.tbPaliwo6 = ((System.Windows.Controls.TextBlock)(this.FindName("tbPaliwo6")));
            this.tbCena1 = ((System.Windows.Controls.TextBlock)(this.FindName("tbCena1")));
            this.tbCena2 = ((System.Windows.Controls.TextBlock)(this.FindName("tbCena2")));
            this.tbCena3 = ((System.Windows.Controls.TextBlock)(this.FindName("tbCena3")));
            this.tbCena4 = ((System.Windows.Controls.TextBlock)(this.FindName("tbCena4")));
            this.tbCena5 = ((System.Windows.Controls.TextBlock)(this.FindName("tbCena5")));
            this.tbCena6 = ((System.Windows.Controls.TextBlock)(this.FindName("tbCena6")));
            this.lpSklepy = ((Microsoft.Phone.Controls.ListPicker)(this.FindName("lpSklepy")));
            this.lpPrzejsciaPapierosy = ((Microsoft.Phone.Controls.ListPicker)(this.FindName("lpPrzejsciaPapierosy")));
            this.lpPapierosy = ((Microsoft.Phone.Controls.ListPicker)(this.FindName("lpPapierosy")));
        }
    }
}

