//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFeRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stacje_benzynoweEntity
    {
        public Stacje_benzynoweEntity()
        {
            this.paliwo_ceny = new HashSet<Paliwo_cenyEntity>();
            this.wyjazdy = new HashSet<WyjazdyEntity>();
        }
    
        public int id_stacje_benzynowe { get; set; }
        public int id_przejscia { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<Paliwo_cenyEntity> paliwo_ceny { get; set; }
        public virtual PrzejsciaEntity przejscia { get; set; }
        public virtual ICollection<WyjazdyEntity> wyjazdy { get; set; }
    }
}
