//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFeRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class KantoryEntity
    {
        public KantoryEntity()
        {
            this.kursy = new HashSet<KursyEntity>();
        }
    
        public int id_kantory { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<KursyEntity> kursy { get; set; }
    }
}
