//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class alkohole
    {
        public alkohole()
        {
            this.alkohol_ceny = new HashSet<alkohol_ceny>();
            this.uaktualnienia_alkohol = new HashSet<uaktualnienia_alkohol>();
        }
    
        public long id_alkohole { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<alkohol_ceny> alkohol_ceny { get; set; }
        public virtual ICollection<uaktualnienia_alkohol> uaktualnienia_alkohol { get; set; }
    }
}
