//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class kantory
    {
        public kantory()
        {
            this.kursy = new HashSet<kursy>();
            this.uaktualnienia_kursy = new HashSet<uaktualnienia_kursy>();
        }
    
        public long id_kantory { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<kursy> kursy { get; set; }
        public virtual ICollection<uaktualnienia_kursy> uaktualnienia_kursy { get; set; }
    }
}
