//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class papierosy
    {
        public papierosy()
        {
            this.papierosy_ceny = new HashSet<papierosy_ceny>();
            this.uaktualnienia_papierosy = new HashSet<uaktualnienia_papierosy>();
        }
    
        public long id_papierosy { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<papierosy_ceny> papierosy_ceny { get; set; }
        public virtual ICollection<uaktualnienia_papierosy> uaktualnienia_papierosy { get; set; }
    }
}
