//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class sklepy
    {
        public sklepy()
        {
            this.alkohol_ceny = new HashSet<alkohol_ceny>();
            this.papierosy_ceny = new HashSet<papierosy_ceny>();
            this.uaktualnienia_alkohol = new HashSet<uaktualnienia_alkohol>();
            this.uaktualnienia_papierosy = new HashSet<uaktualnienia_papierosy>();
        }
    
        public long id_sklepy { get; set; }
        public long id_przejscia { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<alkohol_ceny> alkohol_ceny { get; set; }
        public virtual ICollection<papierosy_ceny> papierosy_ceny { get; set; }
        public virtual przejscia przejscia { get; set; }
        public virtual ICollection<uaktualnienia_alkohol> uaktualnienia_alkohol { get; set; }
        public virtual ICollection<uaktualnienia_papierosy> uaktualnienia_papierosy { get; set; }
    }
}
