//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class uaktualnienia_kursy
    {
        public long id_uaktualnienia_kursy { get; set; }
        public long id_kantory { get; set; }
        public long id_uzytkownicy { get; set; }
        public decimal kurs { get; set; }
        public System.DateTime data { get; set; }
        public long zrealizowano { get; set; }
        public long odrzucono { get; set; }
    
        public virtual kantory kantory { get; set; }
        public virtual uzytkownicy uzytkownicy { get; set; }
    }
}
