//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class uzytkownicy
    {
        public uzytkownicy()
        {
            //this.uaktualnienia_alkohol = new HashSet<uaktualnienia_alkohol>();
            //this.uaktualnienia_kursy = new HashSet<uaktualnienia_kursy>();
            //this.uaktualnienia_paliwo = new HashSet<uaktualnienia_paliwo>();
            //this.uaktualnienia_papierosy = new HashSet<uaktualnienia_papierosy>();
        }
    
        public long id_uzytkownicy { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public string email { get; set; }
        public System.DateTime zarejestrowano { get; set; }
        public Nullable<System.DateTime> ostatnie_logowanie { get; set; }
        public long status { get; set; }
    
        //public virtual ICollection<uaktualnienia_alkohol> uaktualnienia_alkohol { get; set; }
        //public virtual ICollection<uaktualnienia_kursy> uaktualnienia_kursy { get; set; }
        //public virtual ICollection<uaktualnienia_paliwo> uaktualnienia_paliwo { get; set; }
        //public virtual ICollection<uaktualnienia_papierosy> uaktualnienia_papierosy { get; set; }
    }
}
