//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class waluty
    {
        public waluty()
        {
            this.kursy = new HashSet<kursy>();
        }
    
        public long id_waluty { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<kursy> kursy { get; set; }
    }
}
