#pragma checksum "C:\Users\Paweł\documents\visual studio 2013\Projects\WCFeRosja\eRosja\Strony\MainPage.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "9024FC916CA9D25D821CC49C68E0AB24"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Phone.Controls;
using System;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Automation.Peers;
using System.Windows.Automation.Provider;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Imaging;
using System.Windows.Resources;
using System.Windows.Shapes;
using System.Windows.Threading;


namespace eRosja {
    
    
    public partial class MainPage : Microsoft.Phone.Controls.PhoneApplicationPage {
        
        internal System.Windows.Controls.Grid LayoutRoot;
        
        internal System.Windows.Controls.StackPanel TitlePanel;
        
        internal System.Windows.Controls.Grid ContentPanel;
        
        internal System.Windows.Controls.TextBox tbLogin;
        
        internal System.Windows.Controls.TextBox tbHaslo;
        
        internal System.Windows.Controls.Button btnZaloguj;
        
        internal System.Windows.Controls.Button btnZarejestruj;
        
        internal System.Windows.Controls.TextBlock lblInformacja;
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Windows.Application.LoadComponent(this, new System.Uri("/eRosja;component/Strony/MainPage.xaml", System.UriKind.Relative));
            this.LayoutRoot = ((System.Windows.Controls.Grid)(this.FindName("LayoutRoot")));
            this.TitlePanel = ((System.Windows.Controls.StackPanel)(this.FindName("TitlePanel")));
            this.ContentPanel = ((System.Windows.Controls.Grid)(this.FindName("ContentPanel")));
            this.tbLogin = ((System.Windows.Controls.TextBox)(this.FindName("tbLogin")));
            this.tbHaslo = ((System.Windows.Controls.TextBox)(this.FindName("tbHaslo")));
            this.btnZaloguj = ((System.Windows.Controls.Button)(this.FindName("btnZaloguj")));
            this.btnZarejestruj = ((System.Windows.Controls.Button)(this.FindName("btnZarejestruj")));
            this.lblInformacja = ((System.Windows.Controls.TextBlock)(this.FindName("lblInformacja")));
        }
    }
}

