//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class paliwa
    {
        public paliwa()
        {
            this.paliwo_ceny = new HashSet<paliwo_ceny>();
            this.uaktualnienia_paliwo = new HashSet<uaktualnienia_paliwo>();
        }
    
        public long id_paliwa { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<paliwo_ceny> paliwo_ceny { get; set; }
        public virtual ICollection<uaktualnienia_paliwo> uaktualnienia_paliwo { get; set; }
    }
}
