//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class alkohol_ceny
    {
        public long id_alkohol_ceny { get; set; }
        public long id_alkohole { get; set; }
        public long id_przejscia { get; set; }
        public long id_sklepy { get; set; }
        public decimal cena { get; set; }
    
        public virtual sklepy sklepy { get; set; }
        public virtual przejscia przejscia { get; set; }
        public virtual alkohole alkohole { get; set; }
    }
}
