//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eRosja
{
    using System;
    using System.Collections.Generic;
    
    public partial class zmiany
    {
        public zmiany()
        {
            this.cykl_zmian = new HashSet<cykl_zmian>();
        }
    
        public long id_zmiany { get; set; }
        public long id_przejscia { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<cykl_zmian> cykl_zmian { get; set; }
        public virtual przejscia przejscia { get; set; }
    }
}
